name: diy push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * *' # Run every 2 hours

jobs:
  diy_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python Scripts
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        QYWECHAT_ID: ${{ secrets.QYWECHAT_ID }}
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REGION: ${{ secrets.REGION }}
        BUCKET: ${{ secrets.BUCKET }}
      run: 
        |-
          python clashupdate.py && vps.py
