name: diy push

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

    
jobs:
  diy_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 # 替换为所需的Python版本

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: diy push
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        QYWECHAT_ID: ${{ secrets.QYWECHAT_ID }}
      run: 
        # 运行上传脚本
        python club.py
