name: 每天5星新闻提醒

on:
  schedule:
    # Runs every Monday at 00:00 (midnight) UTC
   - cron: '0 12-20 * * *'
  workflow_dispatch:  # 手动触发

jobs:
  send_report:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ 检出代码
        uses: actions/checkout@v4

      - name: 🐍 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 📦 安装依赖
        run: pip install requests beautifulsoup4
             pip install pytz

      - name: 🚀 运行交易报告脚本
        env:
          telegram_bot_token: ${{ secrets.telegram_bot_token }}  # 从 GitHub Secrets 获取 Webhook
          telegram_chat_id: ${{ secrets.telegram_chat_id }}  # 从 GitHub Secrets 获取 Webhook
          wechat_webhook_url1: ${{ secrets.wechat_webhook_url1 }}  # 从 GitHub Secrets 获取 Webhook
          wechat_webhook_url2: ${{ secrets.wechat_webhook_url2 }}  # 从 GitHub Secrets 获取 Webhook
        run: python daynews.py
