name: 处理并上传 Clash YAML

on:
    schedule:
        # 每天上午 10:00 (UTC 时间是 02:00) 运行一次
        - cron: '0 2 * * *'
      workflow_dispatch: # 允许手动点击按钮运行

jobs:
  process_upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖包
        run: pip install requests cos-python-sdk-v5

      - name: 获取 Clash 配置并上传到腾讯云 COS
        env:
          SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          REGION: 'ap-shanghai'
          BUCKET: 'chitu-1251006555'
          WECOM_WEBHOOK: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e75ac7b2-f7e7-45a5-a7b8-0f92390ab020'
        run: python clashupdate.py
